steps:
  - name: 'node:24'
    entrypoint: 'npm'
    args: ['ci']
    dir: 'frontend'

  - name: 'node:24'
    entrypoint: 'npm'
    args: ['run', 'lint']
    dir: 'frontend'

  - name: 'node:24'
    entrypoint: 'npm'
    args: ['test']
    dir: 'frontend'

  - name: 'node:24'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'frontend'
    env:
      - 'VITE_FIREBASE_API_KEY=AIzaSyCwAA7MJGTsn6wNMsJrPwSj_Lt3d4Sx2Ho'
      - 'VITE_FIREBASE_AUTH_DOMAIN=corgi-8732c.firebaseapp.com'
      - 'VITE_FIREBASE_PROJECT_ID=corgi-8732c'
      - 'VITE_API_URL=https://corgi-backend-838648453884.asia-northeast1.run.app'

  - name: 'node:24'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'npm install -g firebase-tools && firebase deploy --only hosting --project corgi-8732c'
